services:
  - type: web
    name: newsletter-aggregator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "from app import app, db; app.app_context().push(); db.create_all()" && \
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: DATABASE_URL
        fromDatabase:
          name: newsletter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PASSWORD_SALT
        generateValue: true
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_WEBHOOK_SIGNING_KEY
        sync: false
      - key: MAILGUN_BASE_URL
        value: https://api.mailgun.net/v3
      - key: NEWSLETTER_RECEIVING_EMAIL
        sync: false
      - key: DIGEST_FROM_EMAIL
        sync: false
      - key: DIGEST_FROM_NAME
        value: Newsletter Digest

databases:
  - name: newsletter-db
    databaseName: newsletter
    plan: free
    ipAllowList: [] # allow all 