services:
  - type: web
    name: newsletter-aggregator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      sleep 10 && \
      python -c "
      import time
      from app import create_app, db
      app = create_app('production')
      with app.app_context():
          db.create_all()
      " && \
      gunicorn 'app:create_app()'
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: newsletter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PASSWORD_SALT
        generateValue: true

databases:
  - name: newsletter-db
    databaseName: newsletter
    plan: free
    ipAllowList: [] # allow all 